### ISSUE TITLE
VCRUNTIME140.dll embedded

### ISSUE THREAD

**Issue by edsonitk** [albertosottile/py2exe#14]
Hi,

Would it be possible to embed VCRUNTIME140.dll in the single generated file, so pyinstall does?

**Comment by albertosottile** [comment]
Technically, that should be feasible, providing that you are building on a machine that has the right Visual Studio or the right Visual C++ Redistributable Package installed. 

I am more concerned about the licensing perspective of this, though. `py2exe` should be usable in projects licensed with any free software license, including GPL, and I am not sure about the compatibility of distributing these DLLs with such a license. Hence, to the very least this embedding should be made optional. 

At this point, it would be probably better to warn your users to install the right redistributables (which are required by many different applications, to be honest) than embed those DLLs in your software.

**Comment by edsonitk** [comment]
I have installed the Visual Studio and C ++ Redistributable Package installed.
But is it optional in py2exe?

**Comment by albertosottile** [comment]
At this moment, it is not even optional, these libraries are not embedded in the bundle. Any user of your application should install the Visual C++ Redistributable Package on their system independently. We can discuss changing this in the future, but that is the current behavior of `py2exe`.

**Comment by edsonitk** [comment]
It would be interrating for portability.
Thanks for listening

**Comment by Athanasius** [comment]
From some investigation I did for WiX-based .msi generation I found out that VC140RUNTIME is meant to simply be handled by the machine's Windows Update these days.  There's no .msm file for Visual C Runtime any more for this reason.

**Comment by Et0h** [comment]
If Windows 10 does now distribute VC140RUNTIME through Windows Update then this is a positive move.

For the @Syncplay project we advise that if people get an error then they should install [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587).

There are links to other redistributables at https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads and more obscure redistributable packages are available from https://www.microsoft.com/en-gb/search?q=Visual+C%2B%2B+Redistributable+Package

**Comment by albertosottile** [comment]
Closing this as per the earlier discussion and per the latest @Athanasius comment.

**Comment by rewiaca** [comment]
@albertosottile Could you please suggest where code could be changed for py2exe to use vcruntime140 dll from embeded files and not from files in same directory? Can find any mention of this dll in repo, not quite familiar with C. Thanks!
