### ISSUE TITLE
CACERT.pem cannot be found

### ISSUE THREAD

**Issue by urishab** [albertosottile/py2exe#19]
When using py2exe 0.9.3.1 with the requests package and addressing an HTTPS address we need the CACERT.pem file and it is not found. Instead failing with the following message:

`OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Projects\*****\******\lib\cacert.pem`

This is probably due to the certifi hook copying the cacert.pem file under the name 'lib' (instead of under a folder named 'lib')
Later it looks for that file under a folder named 'lib' and doesn't find it.

I would have made a pull request to change it so the file is plaed without the 'lib' folder but I'm not sure if maybe there's a more elegant way of doing it. If there isn't I'll make a pull request for fixing it.

**Comment by albertosottile** [comment]
You are absolutely right, that hook was not meant to be universal but it was added by me to solve an issue that I had encountered when packaging another software (Syncplay). I am working on a more flexible version of the hook that should work for most setup scripts.

**Comment by albertosottile** [comment]
The new hook should fix this issue. Can you please install the wheels from this address:
https://bintray.com/alby128/py2exe/py2exe/0.9.3.2/view/files?sort=name&order=asc#files/
and tell me if this works for you now? Thanks again for reporting this.

**Comment by urishab** [comment]
it works for me
Uri
