### ISSUE TITLE
assertion failure when importing a specific module from wxPython

### ISSUE THREAD

**Issue by urishab** [albertosottile/py2exe#2]
Hi
This is just what I was looking for: a py2exe port for Python3.6
I'm having an issue compiling my software and have narrowed it down to a simple test case
see the attached test.py prints 'hello' to the screen
but compiling it using py2exe 0.9.3.0 fails with the following message:
```

  File "C:\Projects\pyenv\lib\site-packages\py2exe\mf3.py", line 451, in _scan_opcodes
    assert instructions[-2].opcode == LOAD_CONST

AssertionError

```
my test.py:
```
from wx.lib.agw import ultimatelistctrl
print('hello')

```
my py2exe file:
```
from distutils.core import setup
import py2exe #@UnusedImport
setup( console=[{ "script": "test.py",},],)
```

I compile using:
`python py2exe_test.py py2exe`

python version:
`Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32`

my pip list:
```
Package    Version
---------- -------
Pillow     6.0.0
pip        19.0.3
py2exe     0.9.3.0
setuptools 40.6.2
six        1.12.0
wxPython   4.0.4
```

**Comment by albertosottile** [comment]
Thank you for reporting this. Unfortunately, I will not be able to access my test system at least until next Monday. I will give a look at the test case as soon as possible.

**Comment by urishab** [comment]
thanks
I just upgraded to Python 3.6.8 in case it was bug in Python, still the same issue

**Comment by urishab** [comment]
does py2exe support 64bit python?

**Comment by albertosottile** [comment]
Yes, it does. Use the `win_amd64` wheels, e.g. https://github.com/albertosottile/py2exe/releases/download/v0.9.3.0/py2exe-0.9.3.0-cp36-none-win_amd64.whl. Please open separate issues if you have other question unrelated to the current topic.

**Comment by urishab** [comment]
Here's another case of the same issue (I believe the same issue):

my test2.py:
```
from reportlab.pdfgen.canvas import Canvas
print('hello')

```
my py2exe_test2.py:
```
from distutils.core import setup
import py2exe #@UnusedImport
setup( console=[{ "script": "test2.py",},],)
```

I get the same error:
```
running py2exe
Traceback (most recent call last):
  File "py2exe_test.py", line 3, in <module>
    setup( console=[{ "script": "test.py",},],)
  File "c:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\runtime.py", line 174, in analyze
    target.analyze(mf)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\runtime.py", line 75, in analyze
    modulefinder.run_script(self.script)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 86, in run_script
    self._scan_code(mod.__code__, mod)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 426, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 138, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 125, in import_hook
    self._handle_fromlist(module, fromlist, caller)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 196, in _handle_fromlist
    self._gcd_import('{}.{}'.format(mod.__name__, x))
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 389, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 420, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\mf3.py", line 451, in _scan_opcodes
    assert instructions[-2].opcode == LOAD_CONST
AssertionError
```

**Comment by urishab** [comment]
going further into this this seems to be a problem with the way py2exe parses the disassembled PYTHON codes.
The following line: (3264)
`    from reportlab.platypus import cleanBlockQuotedText
`
From the file:
reportlab/platypus/paraparser.py
Gives as argument the cleanBlockQuotedText
but this argument is too large to fit in 16bit op code so it is split to 2 op codes (one of which is EXTENDED_ARG) and this doesn't fit with py2exe parsing of opcodes.

This is what the OPCODES look like after disassembly:
```
0 = {Instruction} Instruction(opname='LOAD_CONST', opcode=100, arg=2, argval=0, argrepr='0', offset=9676, starts_line=3264, is_jump_target=False)
1 = {Instruction} Instruction(opname='EXTENDED_ARG', opcode=144, arg=6, argval=6, argrepr='', offset=9678, starts_line=None, is_jump_target=False)
2 = {Instruction} Instruction(opname='LOAD_CONST', opcode=100, arg=1654, argval=('cleanBlockQuotedText',), argrepr="('cleanBlockQuotedText',)", offset=9680, starts_line=None, is_jump_target=False)
3 = {Instruction} Instruction(opname='IMPORT_NAME', opcode=108, arg=100, argval='reportlab.platypus', argrepr='reportlab.platypus', offset=9682, starts_line=None, is_jump_target=False)

```
And when py2exe looks at the unexpected EXTENDED_ARG it expects the LOAD_CONST in its place and fails with the following line:
`                    assert instructions[-3].opcode == LOAD_CONST
`
The problem seems to be lack of support for the OPCODE EXTENDED_ARG in the mf3.py module.

I changed the code to the following and it seems to now be working:
 ```
               if c == IMPORT_NAME:
                    ind = len(instructions)-2
                    while instructions[ind].opcode == EXTENDED_ARG:
                        ind -= 1
                    assert instructions[ind].opcode == LOAD_CONST
                    fromlist = instructions[ind].argval
                    ind -= 1
                    while instructions[ind].opcode == EXTENDED_ARG:
                        ind -= 1
                    assert instructions[ind].opcode == LOAD_CONST
                    level = instructions[ind].argval
                    name = inst.argval
                    yield "import", (level, fromlist, name)
```

**Comment by albertosottile** [comment]
Thank you for pursuing this! I expected something similar, but without a working setup I cannot not do much. I'll test the fix and probably push it as soon as possible.

**Comment by albertosottile** [comment]
Thank you for fixing this, I just tested your patch and confirmed that it works perfectly. Would you like to submit a PR or do you prefer me to commit it to the repository?

**Comment by urishab** [comment]
hi thanks
i'm quite new to git so just go ahead and commit it yourself

**Comment by urishab** [comment]
managed to open a pull request with the code change!

**Comment by albertosottile** [comment]
Thank you for finding this issue and for your PR. I really appreciated your contribution. I hope you will be able to use `py2exe` for your projects.
