### ISSUE TITLE
updates to readme 

### ISSUE THREAD

**Issue by DirkOsswald** [albertosottile/py2exe#25]
While following the build instructions from the readme file I stumbled upon some issues:

### Link to VC++ build tools is broken
I found the required information on https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29
instead.

### Had to install some packages. 

Could you include the necessary dependencies in the readme file?
Here is what I had to install into a fresh python 3.7 windows installation:
- setuptools (was actually preinstalled, but could be mentioned anyway)
- pefile
- cachetools
- wheel

For newbies you could include the installation instructions like this:
`pip3 install setuptools wheel pefile cachetools`

Thank you very much for your effort in keeping py2exe alive! Please keep up the good work.

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. You are absolutely right, those packages are indeed required to run py2exe. However, for newbies, I would recommend installing prebuilt wheels from https://github.com/albertosottile/py2exe/releases , as they do not require to have a working copy of Visual Studio installed. In addition, if you install from the wheels, the dependencies are installed automatically by `pip`.

A better solution, long term, would be to publish these wheels on PyPI, but this would require contacting and getting authorization from the original maintainers of py2exe, and I feel this project is not mature enough for that. 

I will revise the README file according to this issue and this comment.

**Comment by albertosottile** [comment]
Closed in 24d7134.
