### ISSUE TITLE
Failing to build py2exe on python3.8

### ISSUE THREAD

**Issue by snodo** [albertosottile/py2exe#30]
When using python3.8 (x64) with the following command:
> python.exe setup.py bdist_wheel

it comes to the an error:

> start.obj : error LNK2001: unresolved external symbol _Py_Dealloc
> build\lib\py2exe\run-py3.8-win-amd64.exe :fatal error LNK1120: 1 unresolved externals

(I used the exact same procedure with python3.7 and it works)

**Comment by albertosottile** [comment]
Thanks, I am aware of this issue and I fixed it already in the `py38` branch. If you want, you can cherry-pick the commit 1ec361d7b347a77d166264950398f6fae171fd1e and try to recompile. Otherwise, I plan to release the wheels for the next version (0.9.4.0) also for Python 3.8.

**Comment by snodo** [comment]
Oops, didn't look for a branch.
It worked to build and install the wheel in python3.8 with that branch.
Thanks a lot!

(Had to do a few changes to get pywin32, pycryptodome and tinycss2 running, but now everything is working)

**Comment by ahmedtds** [comment]
@albertosottile can you release new version with py3.8 support please

**Comment by albertosottile** [comment]
The release will not come that soon, but if you need to use wheels for Python 3.8 now, you can find the prerelease wheels on Bintray: https://bintray.com/alby128/py2exe/download_file?file_path=py2exe-0.9.4.0-cp38-none-win_amd64.whl

**Comment by ahmedtds** [comment]
> 
> 
> The release will not come that soon, but if you need to use wheels for Python 3.8 now, you can find the prerelease wheels on Bintray: https://bintray.com/alby128/py2exe/download_file?file_path=py2exe-0.9.4.0-cp38-none-win_amd64.whl

thank you for that

**Comment by Nandaka** [comment]
@albertosottile do you have the win32 whl version for python 3.8?

**Comment by albertosottile** [comment]
A wheel for cp38-win32 will be provided with the upcoming release, but I still do not know when that will happen. I am glad that you managed to compile py2exe for this Python version and architecture on your own.

**Comment by alexchandel** [comment]
Any update on 3.8?  2.x is now end-of-lifed, and 3.8 is widespread.

**Comment by mikewolfli** [comment]
Hello albertosottile! Thank you for making this project go-live. Just now, I download it from py38 branch, and build it with vs 2015. Then pip install the whl file. At last I build my project  and run the exe file successfully.I think it's very good.Because if it run error. it will make a error log in the log-file. You can find your error in this log file.

**Comment by albertosottile** [comment]
I released 0.10.0.1 a few days ago with 3.8 support. Hence, I will close this now. Sorry for the delay (the branch was ready for a while but not tested at all).

@alexchandel This fork does not support 2.x at all and has been working since almost the beginning with 3.5, 3.6, and 3.7.
