### ISSUE TITLE
failure to compile with import NumPy AND pywin32 installed

### ISSUE THREAD

**Issue by urishab** [albertosottile/py2exe#4]
Another odd issue I encountered.
Not sure if related or not to the previous Numpy issue.
This time If I import NumPy the file fails to compile using py2exe
It fails when trying to copy the pywin32 dll to the dist folder

Interestingly it only fails if I have pywin32 installed (python package).
If I uninstall pywin32 using pip I don't get the error during compile.
I do however get the error from the other issue when I try to run it.

This is with the mod I applied to py2exe on the previous issue (with the EXTENDED_ARG opcode).

The file test4.py:
```
import numpy
print('hello')

```
The setup file py2exe_test4.py:
```
from distutils.core import setup
import py2exe #@UnusedImport
setup( console=[{ "script": "test4.py",},],
       options={"py2exe": {
       }})

```
I run:
`python py2exe_test4.py py2exe
`
My pip freeze:
```
numpy==1.16.2
py2exe==0.9.3.0
pywin32==224

```
The error I get:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Projects/py2exe/py2exe_test4.py", line 4, in <module>
    options={"py2exe": {
  File "c:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Projects\py2exe\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Projects\py2exe\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 273, in _run
    builder.build()
  File "C:\Projects\py2exe\pyenv\lib\site-packages\py2exe\runtime.py", line 264, in build
    self.copy_files(destdir)
  File "C:\Projects\py2exe\pyenv\lib\site-packages\py2exe\runtime.py", line 508, in copy_files
    assert mod.__file__.endswith(EXTENSION_SUFFIXES[0])
AssertionError

```
During the error these are the values of the local parameters:
`mod = Module(pywintypes, 'C:\\Projects\\py2exe\\pyenv\\lib\\site-packages\\pywin32_system32\\pywintypes36.dll')
`

**Comment by albertosottile** [comment]
To be honest, I have always used `pypiwin32` and I had no issues embedding that module with `py2exe`. I'll investigate this issue but, in the meantime, could you try to use `pypiwin32` instead and see what happens?

**Comment by urishab** [comment]
first time I hear about these issues with pywin32.
But you were right, simply installing pypiwin32 solves the problem.

**Comment by albertosottile** [comment]
TIL that `pypiwin32` actually acts as a shim to install `pywin32` itself, so when you install `pypiwin32` you should actually have both. So I do not understand what could have caused this issue.

Anyway, the issue hints to a mismatch between the file extension reported by the loaded module itself (`.dll`) and the expected extension for a python module library (`.pyd`). 

At the moment, however, I am unable to reproduce this bug. I tried to pack the test script with both packages installed (`pywin32` and `pypiwin32`) and after deleting the second, no bug. I also tried to include in the `py2exe_test4.py` script a module from the package (I chose `win32pipe`) but the packaging still works in both cases.

**Comment by urishab** [comment]
yes I also saw a requirement for pypiwin32 is pywin32
I tried and couldnt' reproduce the error anymore.
I guess it's because of pypiwin32 even though I use virtual environment

you can close it I guess

**Comment by urishab** [comment]
I just found out that I still get the exception when I launch the py2exe from my PyCharm using debug mode.
When I run it using Run mode there's no exception.
I have no idea why.

Installing pypiwin32 doesn't help.
It still fails with assert if I launch it in debug.

Reading the docs it seems that the assertion should work the same unless I specify the -O flag to python to ignore assertions but somehow it is ON by default.

In any case the py2exe succeds in building the executable and it runs fine so I don't see how the assertions makes a difference.
Perhaps there is another nuance that I'm missing with my test that would fail later. Not sure. Or perhaps the assertion is too rigid.

Not sure if this should be considered an issue though.

**Comment by albertosottile** [comment]
If I had to guess, I would say that the debug mode of PyCharm interferes with the libraries loaded by the packages and sought by `mf3`. It makes sense though that `pypiwin32` did not solve the issue, because it literally contains no code. 

> In any case the py2exe succeds in building the executable and it runs fine so I don't see how the assertions makes a difference.

Is there any advantage in running a frozen executable built with `py2exe` when PyCharm was in debug mode? Otherwise, I would say to just avoid using this mode for freezing software. I am not a user of PyCharm, so I cannot be of much help here.

**Comment by urishab** [comment]
I just tested it and you're right. It has to do with the PyCharm debugger. The assertions are not disabled.

I wasn't trying to run a frozen executable in debug mode, rather the py2exe compilation process. That's useful to debug py2exe issues.

**Comment by albertosottile** [comment]
> I wasn't trying to run a frozen executable in debug mode, rather the py2exe compilation process. That's useful to debug py2exe issues.

What are the extra data provided when running `py2exe` with PyCharm in debug mode?

**Comment by urishab** [comment]
I was using the debug mode to debug the OPCODE issue for example.
Just generally debugging a process is better than running it through. 
Breakpoints, introspection, etc...
