### ISSUE TITLE
Custom Boot Script not supported

### ISSUE THREAD

**Issue by xdesai** [albertosottile/py2exe#40]
After digging through the code a bit it seems like custom_boot_script is not currently a supported feature on this fork, but I wanted to reach out and double check just in case I was missing something.
This is a feature we were using on a previous version and I'd be interested to know if there was a technical limitation or just resource/time limitation that prevented it from being added. Just want to save myself some pain before I work on a PR or fork.
Thanks!

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. I have never actually used this feature and, judging from the entry in the original TODO text file, it was never ported to Python 3.x to begin with. I have nothing against this feature per se, so you are welcome to prepare and submit a PR for it if you want.

**Comment by albertosottile** [comment]
Closing this as no progress has happened so far. Feel free to reopen the issue and/or submit a PR if there are any news about this feature.
