### ISSUE TITLE
py2exe error with Gui app

### ISSUE THREAD

**Issue by nibzy26** [albertosottile/py2exe#44]
Hi, 
I am using Python2.7 and My setup.py looks like this 
from distutils.core import setup

import py2exe

setup (
    name='dcd',
    description="Script to test pubsub for packaging",
    version="0.1",
    
    console=[{'script': "dcd6.py",
               "icon_resources": [(1, "icon.ico")]
            }],
    options={ 'py2exe': {
                'packages': 'encodings, pubsub,wx,sys,os,re,socket,ctypes,webbrowser,ftplib,time,threading,select,xml.etree.ElementTree,datetime',
                'includes': None}
            },
    data_files=[("bitmaps",["logo.jpg"])],        
    )   

------------------------------
in my dcd6.py script I have many imports like 

import wx
import sys
import os
import re
import socket
import ctypes
import webbrowser
from ftplib import FTP
import time
from threading import Thread
#from wx.lib.pubsub import setupkwargs
import pubsub
from pubsub import pub 
from wx.lib.mixins.listctrl import CheckListCtrlMixin
import sys
import select
import xml.etree.ElementTree as ET
import datetime

------------------------------------------
when i try to run py2exe  I get this error 
Kindly advise how can I fix it  Many Thanks

C:\Python27\Dante Config Downloader>python setup.py py2exe
running py2exe
*** searching for required modules ***
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    data_files=[("bitmaps",["logo.jpg"])],
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 243, in run
    self._run()
  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 296, in _run
    self.find_needed_modules(mf, required_files, required_modules)
  File "C:\Python27\lib\site-packages\py2exe\build_exe.py", line 1333, in find_needed_modules
    os.path.walk(path, visit, packages)
  File "C:\Python27\lib\ntpath.py", line 266, in walk
    names = os.listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by albertosottile** [comment]
Closing as still concerns the original py2exe (this fork does not support Python 2.x).
