### ISSUE TITLE
_ssl hook support for virtualenv

### ISSUE THREAD

**Issue by nchidsey** [albertosottile/py2exe#45]
The `DLLs` directory isn't created for each virtualenv, so the `libssl-*.dll` and `libcrypto-*.dll` files the hook looks for need to be pulled from the parent/global python installation, which is where the `_ssl.pyd` comes from.  Perhaps those file paths could be formed using `module.__file__`?

**Comment by albertosottile** [comment]
Thanks for reporting this. At the moment, building from `virtualenv` is not supported (it has never worked also with upstream `py2exe`).

I have a `distutils` branch in this fork in which I am playing with this feature in my spare time but, I am afraid any concrete development on this front is still way ahead. Hence, for the moment I am closing this issue.
