### ISSUE TITLE
certifi cacert.pem included at wrong path

### ISSUE THREAD

**Issue by Athanasius** [albertosottile/py2exe#47]
The new py2exe 0.10.0 (yay! Python 3.8 support!) places the cacert.pem file from `certifi` in the wrong location.

py2exe puts it in the root of the application structure when certifi is expecting it in a `certifi` folder:

```py
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'certifi\\cacert.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'certifi\\cacert.pem'
```

py2exe: py2exe-0.10.0.0-cp38-none-win32.whl
python: 3.8.6 (x86 / 32-bit)
certifi: 2020.6.20

There's nothing in out setup.py mentioning certifi to modify py2exe behaviour.  Relevant section (we have some MSI building and appcast stuff too) of setup.py:

```py
    OPTIONS =  { 'py2exe':
                 {'dist_dir': dist_dir,
                  'optimize': 2,
                  'packages': [
                      'requests',
                      'sqlite3',        # Included for plugins
                  ],
                  'includes': [
                      'dataclasses',
                      'shutil',         # Included for plugins
                      'timeout_session',
                      'zipfile',        # Included for plugins
                  ],
                  'excludes': [ 'distutils', '_markerlib', 'optparse', 'PIL', 'pkg_resources', 'simplejson', 'unittest' ],
              }
    }

    DATA_FILES = [
        ('', [
            'WinSparkle.dll',
            'WinSparkle.pdb',   # For debugging - don't include in package
            'EUROCAPS.TTF',
            'Changelog.md',
            'commodity.csv',
            'rare_commodity.csv',
            'snd_good.wav',
            'snd_bad.wav',
            'modules.p',
            'ships.p',
            'stations.p',
            'systems.p',
            '%s.VisualElementsManifest.xml' % APPNAME,
            '%s.ico' % APPNAME,
            '%s/DLLs/sqlite3.dll' % (sys.base_prefix),
            'EDMarketConnector - TRACE.bat',
        ]),
        ('L10n', [join('L10n',x) for x in os.listdir('L10n') if x.endswith('.strings')]),
        ('plugins', PLUGINS),
    ]

setup(
    name = APPLONGNAME,
    version = VERSION,
    windows = [ {'dest_base': APPNAME,
                 'script': APP,
                 'icon_resources': [(0, '%s.ico' % APPNAME)],
                 'company_name': 'EDCD',  # WinSparkle
                 'product_name': APPNAME,  # WinSparkle
                 'version': BASEVERSION,
                 'product_version': VERSION,
                 'copyright': COPYRIGHT,
                 'other_resources': [(24, 1, open(APPNAME+'.manifest').read())],
             } ],
    console = [ {'dest_base': APPCMDNAME,
                 'script': APPCMD,
                 'company_name': 'EDCD',
                 'product_name': APPNAME,
                 'version': BASEVERSION,
                 'product_version': VERSION,
                 'copyright': COPYRIGHT,
                 'other_resources': [(24, 1, open(APPCMDNAME+'.manifest').read())],
             } ],
    data_files = DATA_FILES,
    options = OPTIONS,
)
```

Re: the sqlite3.dll thing, I'll look into if I can do this another way now with py2exe 0.10.0.

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. Could you check the text formatting? It’s quite confusing, at the moment...

Very sad story: `certifi` is actually part of the test chain on AppVeyor... and the test it’s indeed failing 🤦🏻‍♂️. For some reason, though, AppVeyor is not failing the build. I will check this and the issue ASAP.

**Comment by Athanasius** [comment]
> Hi, thanks for reporting this. Could you check the text formatting? It’s quite confusing, at the moment...

Ah yes, I keep forgetting that GH's idea of MD wants closing triple-backtick on a line of its own.  Fixed.

> Very sad story: `certifi` is actually part of the test chain on AppVeyor... and the test it’s indeed failing 🤦🏻‍♂️. For some reason, though, AppVeyor is not failing the build. I will check this and the issue ASAP.

I *did* wonder how this had slipped through, given `certifi` is almost certainly included for us due to `requests` and that will be a popular module.

**Comment by albertosottile** [comment]
Apperently, it is patch release time but, before, I would like you to test the patched wheels. Could you download the wheel you need from https://bintray.com/alby128/py2exe/py2exe/0.10.0.1#files and run the same test again? (they should cover for both the `certifi` and the `sqlite` issues).

Thank you very much for your help.

**Comment by Athanasius** [comment]
Yup, that's working.  I can now run the packaged .exe without errors, including some code then running that utilises sqlite with the line:

```py
'%s/DLLs/sqlite3.dll' % (sys.base_prefix),
```
removed from our setup.py.  And a `requests` mediated connection has also definitely worked without errors.
