### ISSUE TITLE
Pyside2 / Qt for python compatibility

### ISSUE THREAD

**Issue by rnedelec** [albertosottile/py2exe#8]
Hello,
I find myself in a situation somewhat similar to nvda project's (described in https://github.com/nvaccess/nvda/issues/8375).
I found your fork through the above mentionned issue and this is great news for me.
However, I couldn't find the information about the compatibility of this fork with Pyside2 (Qt for python). Is it compatible ?
Thank you in advance for your answer.

**Comment by albertosottile** [comment]
Hi,
technically, this fork is fully compatible with the latest version (5.12.3) of PySide2. As an example, we are using in the packaging of [Syncplay](https://syncplay.pl) for Windows. However, there are some caveats regarding the packaging procedures. 

First, the whole package has to be imported (by adding PySide2 in options/packages in your setup script), as `py2exe` does not have a reliable way to analyze the C++ imports in PySide2 to derive interdependencies between its submodules. This leads to a large size of the bundle, with lots of files that typically are not needed to run your code. Currently, the best approach is to manually remove the files until you find a minimal subset of Qt libraries and bindings that are needed to run your project. Once you have done that, you can automatize the process as done e.g. [here](https://github.com/Syncplay/syncplay/blob/7862c27d541f46964f7c20184aca90492393de40/buildPy2exe.py#L617).

Second, Qt5 plugins are not automatically imported and some of these are necessary to run any GUI software based on PySide2. Again, you could copy these files manually in your bundle or using a function in your setup script as done e.g. [here](https://github.com/Syncplay/syncplay/blob/7862c27d541f46964f7c20184aca90492393de40/buildPy2exe.py#L643). I think I will provide this feature directly in the fork in a future release.

I hope I answered your doubts. If not, please feel free to ask me any question.

**Comment by rnedelec** [comment]
Great, thanks a lot for this detailed answer. I will try this on our Python 3 migration process.
